### PR TITLE
Add mysql options for docker

### PR DESCRIPTION
**Pull request by sag5515**
We are using docker in development environment.
However, trying to deploy from the host machine in the docker environment causes an error in the existing mysql connection option.
I think the following is a close problem.
https://github.com/welaika/wordmove/issues/421

So I added an option to solve it.

### CODE REVIEW

**Comment by sag5515** [comment]
Can I loosen the AbcSize value?

**Comment by pioneerskies** [comment]
Hey I’m sorry to not being responsive, but I’m not active on the project these weeks. I’ll be really soon and I’ll evaluate and comment you kind PR.

Thanks!

**Comment by pioneerskies** [comment]
I have a big question: why aren't you using the already supported `mysqldump_options` in your movefile in order to add the `--protocol` flag to the command through `movefile.yml`?

https://github.com/welaika/wordmove/wiki/movefile.yml-configurations-explained

**Comment by pioneerskies** [comment]
If I could ask myself, because you need to set protocol during import also, not just during export. Am I right? If yes, I anyway think that implementing a specific option for `mysqldump` is not useful, since you can pass options thought `movefile.yml`.

In order to support custom options during import (thus for the `mysql` command`) I'd like to have a similar approach to the `mysqldump_options`; something like having both `mysqldump_options` and `mysqlimport_options`, instead of achieving a new config just for a specific flag, this way we could have free custom options also during import operations.

If I am not right, sorry :P

Let me know what do you think, please. And moreover thanks for your contribute.

**Comment by sag5515** [comment]
Thank you for reviewing.

> If I could ask myself, because you need to set protocol during import also, not just during export. Am I right?

yes!
Certainly it is more beautiful to match with export options.
Because this purpose can not be attained with this pull request, it closes.

**Comment by pioneerskies** [comment]
@sag5515 will you make a new PR? Please, feel free to contact me if you need any help or open an issue as a feature request if you want me to schedule myself the implementation: better supporting docker environments is in our plans (with the new and WIP https://github.com/welaika/docker-wordmove also)

**Comment by sag5515** [comment]
I'm sorry.
My job is busy right now.
Because we are achieving our purpose with pull request on above, it is working in production environment, therefore priority is not high.
So it is not likely to be fixed soon and will not make a new pull request.

We support a wonderful attempt corresponding to the docker environment!

**Pull request closed without merging**
