### PR TITLE
Update README.mdown

### PR DESCRIPTION
**Pull request by dsgnr**
Added some information about when wp-content folder is called something else.

### CODE REVIEW

**Comment by pioneerskies** [comment]
Hi @dsgnr !

You cannot imagine how much sounds cool to see someone interested in improving the docs! I'm really thrilled about it! :D

Just a couple thoughts follow.

Recently I've re-written a big part of the documentation, starting from the README. I was concerned about how long and fat it was getting and I had moreover the need to add additional informations.
In order to slim it a bit and respond to my needs I decided to write a number of wiki articles and thus rewriting the README I put there references to the specific wiki pages.

For example in the README I reported just few Movefile's options, mostly with the intent to explain its structure and it functionalities, but all - hopefully - the supported configurations are linked at the end of the paragraph (and the link points [here](https://github.com/welaika/wordmove/wiki/Movefile-configurations-explained)).

Said that I'm quite open to discussions and new ideas and critics, I'd like to ask you: why you decided to put additional information inside the RADME rather than inside the wiki page?

I'm really thankful for your effort in getting a better documentation

**Comment by dsgnr** [comment]
Hello @pioneerskies

I did update a small part of the wiki too - maybe I have done it wrong and it has just updated it without the need of approval?

Being fairly new to using gems like this to improve my workflow, I was unfamiliar with how it works so it was a massive learning curve for me believe it or not. 

I was able to work out how to do everything by reading the README and i only looked at the wiki when I got stuck. 

The only issue I had was when I had changed the path of the WP-content folder, which I do on every installation. I couldn't work out why pushing or pulling the files was renaming it, thus breaking the site. 

I just thought maybe if added a line in both the README and wiki that the paths had to be specified in all environments then everything will work correctly. 

Maybe it's simple for others but this caught me out big time!

This gem has been invaluable so I am thrilled to be able to contribute where I can and I will do my best to help if I am able. 

It saves so much time and as a backup of the database is kept in the content folder too, this is also handy to commit to git to keep an accurate version control of the database and theme files. I've always found a struggle to do before as it was always so labour intensive and time consuming before and needed different tools to do. 

 :)

Thanks, Dan

**Comment by dsgnr** [comment]
Expanding from my message above. Would it not be clearer to new users by putting the paths: part in all environments by default when a new Wordmove file is created?

**Comment by delphaber** [comment]
@dsgnr thx. I had to manually edit the Readme since there were some conflicts.

**Pull request closed without merging**
