### PR TITLE
Fix for subdirectory multisite.

### PR DESCRIPTION
**Pull request by torounit**
Issue #45.
Fix for subdirectory multisite.
Replace domain in dump.sql.
Domain is created from vhost in Movefile.

### CODE REVIEW

**Comment by AndreaBarghigiani** [comment]
Good job man! Thank you!

**Comment by esad** [comment]
It would be nice if we could also rewrite ports. I have a local installation at `localhost:3000`, and port doesn't get rewritten to 80 when pulling/pushing to production, because only "host" is replaced.

**Comment by esad** [comment]
Something along these lines should do the job:

https://github.com/esad/wordmove/commit/608133498b8e4856eda1be45a3fa67113c775f62

**Comment by esad** [comment]
Any update on merging this one?

**Comment by dbeja** [comment]
Any updates on this?

**Comment by kaizokou** [comment]
Hello guys,is this branch ready to use ?

**Comment by pioneerskies** [comment]
Hi there @kaizokou @esad @torounit @dbeja and @AndreaBarghigiani ! :)

Unfortunately we are not able to understand in depth what is the need behind this pull request. Probably because we almost never used subdirectory nor multisite.

Could you please elaborate on what should be translated to what? A little example with strings should suffice, but a snippet from the DB and some steps to reproduce would be appreciated.

Particularly we have to understand why and where the `replace_vhost!` method isn't enough to face your needs.

Thanks in advance

**Comment by torounit** [comment]
Hi @pioneerskies !

"domain" column exist in wp_blogs table when multisite. 
If not match the domain between DOMAIN_CURRENT_SITE, ocuur database connection error.

By removing "http://" from vhost in Movefile,  the problem can be solved  for the time being. 
But, can not move to the https from http.

**Comment by tomathyg** [comment]
This fix is working great.

In case it hasn't been made clear, the replace_vhost! method is insufficient because it search and replaces the URLs, including http:// or https://. In a subdirectory multisite (and presumably a subdomain multisite), the wp_blogs table lists just the domains (in the domain column), without http:// or https://, so these fields are missed. The same thing is true of the wp_site table, which contains the main site domain.

Seems like a very simple but valuable fix to me.

**Comment by pioneerskies** [comment]
@tomathyg thanks for your followup.

`replace_vhost!` should search and replace for what is filled in the `Movefile`, can't you confirm this? As far as i can see, we had a poor naming when we choosen `vhost` as the key in `Movefile`; it'd be better to name it **domain**.

In this PR the approach is ok for the new feature, but it lacks something:

if we put the domain, not a URI in the `vshost` key

```ruby
irb(main):001:0> vhost = 'example.com'
=> "example.com"
irb(main):003:0> require 'uri'
=> true
irb(main):004:0> URI(vhost)
=> #<URI::Generic example.com>
irb(main):005:0> URI(vhost).host
=> nil
```

it will work if we used a URI in the `vhost` key:

```ruby
irb(main):006:0> vhost = 'http://example.com'
=> "http://example.com"
irb(main):007:0> URI(vhost).host
=> "example.com"
```

So this PR should not just ensure that the plain domain will be get replaced, but also that the `vhost` key **must** be a complaint URI.

Just to be clearer: atm you could also fill `vhost` with the string "happy new year", and that string will be replaced in the DB. So we have design decision in front of us: should we enforce `vhost` to be something? A URI? A plain domain? A plain domain is not a programmatically understandable format I think...

Just to be clearestest®: atm if you use a plain domain inside `vhost` you should've already fixed the problem this PR is trying to fix.

Comments?

**Comment by tomathyg** [comment]
Yes, using a plain domain as the vhost does indeed solve the problem.

However, I think it is useful to at least be able to specify http:// or https:// as that may differ between servers, so if we're going to enforce something then I think it should be a URI.

**Comment by tomathyg** [comment]
As torounit pointed out, including http:// or https:// in the Movefile is useful if you want to switch from one to the other.

**Pull request closed without merging**
