### PR TITLE
Updated line 55 of movefile.yml generator.

### PR DESCRIPTION
**Pull request by elebumm**
The comment tag (#) is on --itemize-changes throwing an error that you will have to catch if not seen.

### CODE REVIEW

**Comment by elebumm** [comment]
I use the `rsync_options` and a couple of times I ran into an error because the `#` was attached to the end of the last argument. My pull request just adds a single space so that this error can't happen when generating a movefile.

**Comment by pioneerskies** [comment]
Hi @elebumm ,

thanks for your kind and smart PR :)

Don't you think an even better solution should be to enclose in single quotes the string? Actually the fact that it works w/o quotes is just because we do not have hostile characters :)

Let me know. If you do not have the time I will anyway merge this one since it is 👍

**Comment by elebumm** [comment]
Thanks for the reply @pioneerskies! I am a little confused what you mean. Did you mean to include the `--verbose --itemize-changes` in single quotes?

**Comment by elebumm** [comment]
Added the single quotes to the lines that included arguments. Let me know if that was what you are talking about. Always happy to help to the best of my abilities.

**Pull request merged**
