### PR TITLE
Added support for mu-plugins directory

### PR DESCRIPTION
**Pull request by connormckelvey**
Added support for mu-plugins directory.
Tested and works fine.

Please don't mistake this as a duplicate. I didn't realize that v1.3.0 was the development branch and I cannot figure out how to delete my original pull request to the master branch.

### CODE REVIEW

**Comment by delphaber** [comment]
Thank you very much :+1:

**Comment by joeguilmette** [comment]
It would be pretty amazing if this could be rolled into the --pre gem.

**Comment by pioneerskies** [comment]
@joeguilmette working on this within the day.

**Comment by pioneerskies** [comment]
@connormckelvey @delphaber @joeguilmette the PR should be at public disposal with `gem install wordmove --pre`.

Please, test it and report encountered issues :)

**Comment by joeguilmette** [comment]
Tested in front of a live studio audience. Works like a charm!

**Comment by trippo80** [comment]
There's actually an issue with this one. Pushing mu-plugins doesn't care about the wp_content path setting in the Movefile. 

In my case - pushing plugins pushes from /web/app/plugins, but when pushing mu-plugins it tries to push from /wp-content/mu-plugins.

**Comment by connormckelvey** [comment]
@trippo80 I'll take a look at this.

**Comment by trippo80** [comment]
@connormckelvey Thanks - any progress yet?

**Comment by kevinwhoffman** [comment]
Is the mu-plugin path that @trippo80 mentioned still an issue?

**Comment by trippo80** [comment]
@kevinwhoffman It's still an issue yes. I've stopped using Wordmove now though and using Deployer instead because we've moved to production for this project. I think Wordmove is great for development and test sites so it would be really nice if this could be fixed.

**Pull request merged**
