### PR TITLE
Added to put ruby code support in Movefile

### PR DESCRIPTION
**Pull request by kenchan0130**
Hi
As it is now, can't load a YAML file containing ERB like a basic YAML file.
So that, I added to put ruby code support in Movefile.

### CODE REVIEW

**Comment by tuvistavie** [comment]
I would love to see this merged too.

**Comment by Arkham** [comment]
:+1:

**Comment by kenchan0130** [comment]
ping

**Comment by delphaber** [comment]
@kenchan0130 thank you! Merged in https://github.com/welaika/wordmove/commit/13c9f215c5e0c1f49119e550ce4cbe2755d3b9c4

**Pull request closed without merging**
